services:

  
      

  authentication: 
    build:
      context: authentication
    ports: 
      - '8000:8000'
    volumes:
      - ./authentication:/app
    environment:
       WEB_DOCUMENT_ROOT: /app/authentication
    depends_on:
      - postgres_db
    links:
    - postgres_db

  networking:
    build:
      context: networking
    ports:
      - '5555:5555'
    volumes:
      - ./networking:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/networking
    
    
  postgres_db:
      image: postgres:16.0-alpine
      container_name: postgres_db
      hostname: postgres_db
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=${SQL_NAME}
        - POSTGRES_USER=${SQL_USER}
        - POSTGRES_PASSWORD=${SQL_PASSWORD}  
      ports:
        - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres_db
    ports:
      - 9090:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
volumes:
  postgres_data:


