



CLIENT_ID_BYTELENGTH:int = 16
GAME_DATA_BYTELENGTH:int = 1024
MAX_EVENT_HEAD_SIZE_BYTES:int  = 3
MAX_EVENT_DATA_SIZE_BYTES:int = 2048
EVENT_HEAD_ID_MASK:int = 0xff
EVENT_HEAD_DATA_LENGTH_MASK:int = 0xffff00

HOST:str = "localhost"
PORT:int = 5555