#!/usr/bin/python3



import queue
from networking import NetworkClient, NetworkConst, NetworkEvent



recieved = queue.Queue(maxsize=10)

nc = NetworkClient(NetworkConst.HOST, NetworkConst.PORT, recieved)

nc.send(NetworkEvent.MESSAGE, {'from':'me', 'message':'ELLOOOO'})
nc.send(NetworkEvent.MESSAGE, {'from':'me', 'message':'ELLOOOO'})
nc.send(NetworkEvent.MESSAGE, {'from':'me', 'message':'ELLOOOO'})


while True:
    
    if recieved.empty():
        continue

    event = recieved.get()

    print(event)