#!/usr/bin/python3



from networking import NetworkClient, NetworkConst, NetworkEvent


nc = NetworkClient(NetworkConst.HOST, NetworkConst.PORT)


while True:
    nc.sync(NetworkEvent.LOBBY_CREATE, {'lobbyName':'ddt'})